export const FORMATS: { [index: string]: string[] } = {
  image: ['.jpg', '.gif', '.png'],
  // image: ['.jpg', '.jpeg', '.gif', '.png', '.tiff', '.heic', '.hevc', '.heif', '.tif'],
  // video: ['.mp4', '.mov', '.flv', '.avi', '.webm', '.mkv', '.wmv', '.mts'],
  // audio: ['.mp3', '.wav'],
  // doc: ['.doc', '.docx'],
  // excel: ['.xls', '.xlsx'],
  // ppt: ['.ppt', '.pptx'],
  // pdf: ['.pdf'],
  // txt: ['.txt'],
  // odt: ['.odt'],
  // csv: ['.csv'],
  // archive: ['.rar', '.zip', '.7z', '.gz', '.bz2', '.tar'],
  // folder: ['folder'],
}
