export default {
  home: '/',
  artworks: '/artworks',
  blog: '/blog',
  artworkAccountSettings: '/artworks/account-settings',
  artworkDetails: '/artworks/:id',
  dashboard: '/artworks/dashboard',
  sellNFT: '/artworks/sell',
  createNFT: '/artworks/create',
  constructor: '/artworks/constructor',
  tradingHistory: '/artworks/trading-history',
  bids: '/artworks/my-bids',
  bidDetails: '/artworks/my-bids/:id',
  sales: '/artworks/my-sales',
}
