export default {
  home: '/',
  artworks: '/artworks',
  artworkDetails: '/artworks/:id',
  blog: '/blog',
  artworkAccountSettings: '/account-settings',
  dashboard: '/dashboard',
  sellNFT: '/sell',
  createNFT: '/create',
  constructor: '/constructor',
  tradingHistory: '/trading-history',
  bids: '/my-bids',
  bidDetails: '/my-bids/:id',
  sales: '/my-sales',
  contentManagement: '/content-management',
  makeOffer: '/make-offer',
  privacyPolicy: '/privacy-policy',
  aboutDAF: '/about-daf',
  communityGuidelines: '/guidelines',
  termsOfService: '/terms-of-service',
  myAlbum: '/my-album',
}
