import React from 'react'
import AuxiliaryPage from '../../index'
import { Box, Link, Typography } from '@material-ui/core'
import { useStyles } from '../../styles'
import { NavLink } from 'react-router-dom'
import routes from '../../../../routes'

export default function DAFPage() {
  const classes = useStyles()
  const headerInfo = [
    'Using, sending tokens to, receiving tokens from, sending messages to or otherwise transacting with the dArtFlex dex system; ',
    'Using, transferring, voting, buying, selling or receiving the DAF token; or ',
    'Participating in the dArtFlex dao or accessing or using a dArtFlex governance module. ',
  ]
  const noticesForClaims = [
    'a physical or electronic signature of the copyright owner or of a person authorized to act on behalf of the copyright owner; ',
    'a clear identification of the copyrighted work that is claimed to be infringing; ',
    'identification of the online material that is claimed to be infringing, including, if possible, a URL representing a link to the material on the dArtFlex website; ',
    'information sufficient to permit dArtFlex Company to contact the complainant, such as email address, physical address, and/or telephone number; ',
    'a statement that the complainant has a good-faith belief that the relevant material is being used in a way that is not authorized by the copyright owner, its agent, or under the law; and ',
    'a statement, made under penalty of perjury, that the above information is accurate, and the complainant is the copyright owner or is authorized to act on behalf of the copyright owner. ',
  ]
  const submissionOfRequests = [
    'the User’s name, address, telephone number, and email address; ',
    'a description of the material that was removed, along with the URL where the content was posted in the Offerings prior to its removal;',
    'the following statement: “I swear, UNDER PENALTY OF PERJURY, that I have a good-faith belief that the material was removed or disabled due to a mistake or misidentification of the material to be removed or disabled”;',
    'a statement that the User consents to the jurisdiction of the Federal District Court for the judicial district in which your address is located, or if the User’s address is outside of the United States, any jurisdiction in which the User may be properly served, and that the User will accept service of process from the person (or their agent) who filed the original DMCA notice; and',
    'the User’s electronic or physical signature. Upon receipt of a valid counter notification, dArtFlex Company will forward it to the party who submitted the original DMCA notification. The original party (or their representative) will then have ten (10) days to notify us that he or she has filed legal action relating to the allegedly infringing material. If dArtFlex 6 Company does not receive any such notification within 10 days, dArtFlex Company may restore the material to the Offerings.',
  ]
  const autonomusEra = [
    'broad distribution of DAF among a diverse cross-section of members of the dArtFlex Community;',
    'the establishment and publication of legally binding dArtFlex DAO Bylaws setting forth the principles, rules, procedures, standards of conduct and other relevant agreements and understandings determining the rights and obligations of DAF holders, the voting of DAF and the operation, coordination and decision-making of the dArtFlex DAO;',
    'the completion of an initial compliance plan for abiding by tax laws and other laws, rules and regulations applicable to the dArtFlex DAO;',
    'upgrading the dArtFlex Governance Module to include a system of dArtFlex DAO Smart Contracts facilitating trust-reduced compliance with the dArtFlex DAO Bylaws and escrowing of fees generated by the dArtFlex DEX System; and ',
    'the negotiation and signing of written commercial agreements between the dArtFlex DAO, on the one hand, and dArtFlex Company and/or other technology companies, on the other hand, through which the dArtFlex DAO can provide funding and direction to such companies for the development, maintenance and operation of the dArtFlex Apps, the licensing of relevant intellectual property such as branding-related trade dress and logos currently owned by dArtFlex Company, and/or other applications and infrastructure necessary or useful for interacting with the dArtFlex DEX System.',
    '(c) Current dArtFlex Governance Module. As of the date of publication of these Terms, the dArtFlex Governance Module is configured as follows: ',
  ]
  const allocationDistribution = [
    '30% of the TotalSupply (the “ReserveSupply”) will be allocated to dArtFlex Company’s affiliates, founders, employees and other personnel (including grant recipients or technology development (sub-)contractors, if applicable) and equity investors;',
    '10% of the TotalSupply (the “AirdropSupply”) will be allocated to bona fide active users the of dArtFlex Apps (based on their trading volume prior to announcement of DAF) and holders of Collectibles eligible to trade on the dArtFlex Apps that were previously involved in sales documented on Dune Analytics; and',
    '60% of the TotalSupply (the “MiningSupply”) will be allocated to users who engage in bona fide, good faith, arm’s-length trading of Collectibles on the dArtFlex Apps, based on the transaction value of such trading.  ',
  ]
  return (
    <AuxiliaryPage title="DAF">
      <>
        <Typography variant={'body2'} component={'div'}>
          DAF token information is an essential part of the{' '}
          <NavLink to={routes.termsOfService} className={classes.navLink}>
            Terms of Use
          </NavLink>
        </Typography>
        <Typography variant={'body2'} component={'div'}>
          It covers the following offerings, including:
        </Typography>
        <ul className={classes.unorderedListInitial}>
          {headerInfo.map((item, index) => {
            return (
              <li className={classes.unorderedListItem} key={index}>
                <Typography variant={'body2'} component={'span'}>
                  {item}
                </Typography>
              </li>
            )
          })}
        </ul>
        <Box className={classes.wrapSection}>
          <Typography className={classes.sectionTitle}>1. CERTAIN DEFINED TERMS AND RELATED INFORMATION </Typography>
          <ul className={classes.unorderedListInitial}>
            <li className={classes.unorderedListItem}>
              <Typography variant={'body2'} component={'span'}>
                “DAF” means the tokens with string constant public name “dArtFlex” and string constant public symbol
                “DAF”, the supply and balances of which are tracked by the smart contract deployed to address
                0x255d578049b0Cc729dceC2F12Fa59867Eb0eCECB
              </Typography>
            </li>
            <li>
              <Typography variant={'body2'} component={'span'}>
                “dArtFlex DEX System” means the bytecodes (aka “smart contracts”) for creating, buying, selling and
                transferring NFTs and Collectibles that are officially supported in the dArtFlex Apps, as they may be
                modified or supplemented from time to time pursuant to Section 2.4.
              </Typography>
            </li>
            <li>
              <Typography variant={'body2'} component={'span'}>
                On the date these Terms were first published, the dArtFlex DEX System comprised the bytecodes deployed
                to the following Ethereum network address{' '}
                <Link
                  href={'https://etherscan.io/address/0x255d578049b0Cc729dceC2F12Fa59867Eb0eCECB#code'}
                  className={classes.navLink}
                >
                  https://etherscan.io/address/0x255d578049b0Cc729dceC2F12Fa59867Eb0eCECB#code
                </Link>
                .
              </Typography>
            </li>
            <li>
              <Typography variant={'body2'} component={'span'}>
                “dArtFlex Governance Module” means the websites, forums, technologies and methods established from time
                to time by dArtFlex Company for the coordination, voting and other official activities of DAF holders in
                connection with the dArtFlex DAO.
              </Typography>
            </li>
          </ul>
        </Box>

        <Typography className={classes.sectionTitle}>2. THE dArtFlex DEX SYSTEM</Typography>
        <Typography variant={'h4'}>2.1 Nature of dArtFlex DEX System.</Typography>
        <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
          The dArtFlex DEX System is a public software utility deployed on Ethereum, which is accessible directly
          through any Ethereum node or indirectly through any compatible Ethereum “wallet” application which interacts
          with such a node. Through the dArtFlex DEX System, any person may create, buy, sell and transfer Collectibles.
        </Typography>
        <Typography variant={'h4'}>2.2 Relationship of dArtFlex DEX System and dArtFlex Apps.</Typography>
        <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
          Interacting with the dArtFlex DEX System does not require use of the dArtFlex Apps, but the dArtFlex Apps
          provide a potentially more convenient and user-friendly method of reading and displaying data (including
          Collectible Metadata) from the dArtFlex DEX System and generating standard transaction messages compatible
          with the dArtFlex DEX System. Interacting with the dArtFlex DEX System through the dArtFlex Apps requires use
          of an independent, User-operated Ethereum wallet application through which the user may broadcast the
          transaction message to Ethereum for processing by Ethereum nodes. The dArtFlex Apps may be used to generate
          standard transaction messages for interacting with the dArtFlex DEX System and transmitting those messages to
          the wallet application. Through the wallet application, a User may broadcast the transaction message to
          Ethereum for processing by Ethereum nodes. Assuming normal operation of the wallet and the relevant Ethereum
          nodes, the Ethereum nodes should utilize such transaction messages to make function calls against the relevant
          bytecode and ultimately include the results of such computations in an Ethereum transaction block, thus
          effectuating an interaction with the dArtFlex DEX System.
        </Typography>
        <Typography variant={'h4'}>2.3 License to Use the dArtFlex Platform.</Typography>
        <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
          Each User, subject to and conditioned upon such User’s acceptance of and adherence to these Terms, is hereby
          granted a non transferable, personal, non-sublicensable license to use the dArtFlex DEX System and dArtFlex
          Apps for their intended purposes.
        </Typography>
        <Typography variant={'h4'}>2.4 Alterations to dArtFlex DEX System.</Typography>
        <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
          dArtFlex Company may from time to time alter the list of smart contracts which are included in the dArtFlex
          DEX System by adding or removing bytecode addresses from the official list of smart contracts supported by the
          dArtFlex Apps, including pursuant to upgrades, forks, security incident responses or chain migrations. In the
          event any bytecode is removed from the dArtFlex DEX System, users would no longer be able to interact with or
          read the data that is associated with such bytecode through the dArtFlex Apps. It is intended (though cannot
          be guaranteed) that Users would continue to be able to interact with such bytecode directly through any
          Ethereum node or indirectly through any compatible Ethereum wallet application, but such interactions may
          require technical expertise beyond those of most Users.
        </Typography>
        <Typography variant={'h4'}>2.5 Content.</Typography>
        <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
          All content on the dArtFlex Platform is created by Users. dArtFlex Company makes no representations or
          warranties as to the quality, origin, or ownership of any content found in the Offerings. dArtFlex Company
          shall not be liable for any errors, misrepresentations, or omissions in, of, and about, the content, nor for
          the availability of the content.
        </Typography>
        <Typography variant={'body2'}>
          dArtFlex Company shall not be liable for any losses, injuries, or damages from the purchase, inability to
          purchase, display, or use of content.
        </Typography>
        <Typography variant={'h4'}>2.6 DMCA Notices for Claims of Copyright Infringement.</Typography>
        <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
          (a) <strong>Takedown Requests.</strong> dArtFlex Company will respond to notices of alleged copyright
          infringement under the United States Digital Millennium Copyright Act. If a User or other person believes that
          their intellectual property rights have been infringed, please notify us immediately. For dArtFlex Company to
          respond, the complaint must provide the following information:
        </Typography>
        <ul className={classes.unorderedListInitial}>
          {noticesForClaims.map((item, index) => {
            return (
              <li className={classes.unorderedListItem} key={index}>
                <Typography variant={'body2'} component={'span'}>
                  {item}
                </Typography>
              </li>
            )
          })}
        </ul>
        <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
          (b) <strong>Submission of Takedown Requests.</strong> Users may submit their takedown requests using the
          Contact us form (LINK) with the subject line “Violation Report / Concerns / Complaints”. If a User believes
          that a User’s material has been removed by mistake or misidentification, the User may provide dArtFlex Company
          with a message containing the following information:
        </Typography>
        <ul className={classes.unorderedListInitial}>
          {submissionOfRequests.map((item, index) => {
            return (
              <li className={classes.unorderedListItem} key={index}>
                <Typography variant={'body2'} component={'span'}>
                  {item}
                </Typography>
              </li>
            )
          })}
        </ul>
        <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
          (c) <strong>Repeat Infringers.</strong> dArtFlex Company reserves the right to terminate the accounts or block
          usage of the Offerings of any party who is a repeat infringer or who is repeatedly charged with infringement.
        </Typography>
        <Typography className={classes.sectionTitle}>3. THE dArtFlex DAO & DAF VOTING </Typography>
        <Typography variant={'h4'}>3.1 Purposes of dArtFlex DAO.</Typography>
        <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
          The dArtFlex DAO was established by dArtFlex Company to foster community among the artists, collectors,
          traders and other users of the dArtFlex Platform (the “dArtFlex Community”) and provide them with a voice in
          how the dArtFlex Platform is run, maintained, marketed, improved and otherwise governed (“Governance
          Decisions”).
        </Typography>
        <Typography variant={'h4'}>3.2 Purposes of DAF.</Typography>
        <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
          DAF are intended to be utilized by the dArtFlex Community to participate in the dArtFlex DAO, including by
          voting on proposed Governance Decisions (“Governance Proposals”). DAF may from time to time be given
          additional uses as determined by dArtFlex Company (in non-binding consultation with the dArtFlex DAO) (during
          the Signaling Era (as defined below)) or by the dArtFlex DAO alone (during the Autonomous Era (as defined
          below)).
        </Typography>
        <Typography variant={'h4'}>3.3 Evolution of dArtFlex DAO.</Typography>
        <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
          The dArtFlex DAO is intended to increase its autonomy and responsibility for influencing Governance Decisions
          over time. The anticipated evolution of the dArtFlex DAO will be divided into two main periods or ‘eras’:
        </Typography>
        <Typography variant={'body2'} component={'span'}>
          <strong>(a) Signaling Era.</strong>
        </Typography>
        <Typography variant={'body2'} component={'div'}>
          The “Signaling Era” began on the date DAF were first distributed to the dArtFlex Community and currently
          remains ongoing. During the Signaling Era, dArtFlex Company will retain ultimate operational and governance
          authority over the dArtFlex Platform while consulting in its discretion with the dArtFlex DAO regarding
          potential Governance Decisions (expressed as Governance Proposals made by dArtFlex Company to the dArtFlex
          DAO) expected to have a material direct impact on the interests of the dArtFlex Community. During the
          Signaling Era, the actions and determinations of the dArtFlex DAO will be treated as non-binding, advisory
          signals to dArtFlex Company regarding the will and interests of the dArtFlex Community, but will not be
          obligated to support or comply with the actions and determinations of the dArtFlex DAO. Nevertheless, dArtFlex
          Company currently anticipates abiding by the dArtFlex DAO’s majority-support determinations regarding
          Governance Proposals that are made by dArtFlex Company during the Signaling Era, provided that the resulting
          Governance Decisions would not reasonably be expected to result in a violation of applicable legal requirement
          or have a material adverse impact on the dArtFlex Platform or dArtFlex Company. During the Signaling Era, DAF
          holders may also initiate their own Governance Proposals (i.e., independent of dArtFlex Company) to the
          dArtFlex DAO. dArtFlex Company will in good faith consider the merits of any such Governance Proposal that
          receives majority support of the dArtFlex DAO during the Signaling Era, but dArtFlex Company cannot currently
          anticipate the likelihood that dArtFlex Company will choose to support or give effect to such independent
          Governance Proposals.
        </Typography>
        <Box mt={3}>
          <Typography variant={'body2'} component={'div'}>
            <strong>(b) Autonomous Era.</strong>
          </Typography>
          <Typography variant={'body2'} component={'span'}>
            The “Signaling Era” began on the date DAF were first distributed to the dArtFlex Community and currently
            remains ongoing. During the Signaling Era, dArtFlex Company will retain ultimate operational and governance
            authority over the dArtFlex Platform while consulting in its discretion with the dArtFlex DAO regarding
            potential Governance Decisions (expressed as Governance Proposals made by dArtFlex Company to the dArtFlex
            DAO) expected to have a material direct impact on the interests of the dArtFlex Community. During the
            Signaling Era, the actions and determinations of the dArtFlex DAO will be treated as non-binding, advisory
            signals to dArtFlex Company regarding the will and interests of the dArtFlex Community, but will not be
            obligated to support or comply with the actions and determinations of the dArtFlex DAO. Nevertheless,
            dArtFlex Company currently anticipates abiding by the dArtFlex DAO’s majority-support determinations
            regarding Governance Proposals that are made by dArtFlex Company during the Signaling Era, provided that the
            resulting Governance Decisions would not reasonably be expected to result in a violation of applicable legal
            requirement or have a material adverse impact on the dArtFlex Platform or dArtFlex Company. During the
            Signaling Era, DAF holders may also initiate their own Governance Proposals (i.e., independent of dArtFlex
            Company) to the dArtFlex DAO. dArtFlex Company will in good faith consider the merits of any such Governance
            Proposal that receives majority support of the dArtFlex DAO during the Signaling Era, but dArtFlex Company
            cannot currently anticipate the likelihood that dArtFlex Company will choose to support or give effect to
            such independent Governance Proposals.
          </Typography>
          <ul className={classes.unorderedListInitial}>
            {autonomusEra.map((item, index) => {
              return (
                <li className={classes.unorderedListItem} key={index}>
                  <Typography variant={'body2'} component={'span'}>
                    {item}
                  </Typography>
                </li>
              )
            })}
          </ul>
          <ul className={classes.dashedList}>
            <li>
              <Box display="flex">
                <Box mr={2}>-</Box>
                <Typography variant={'body2'} component={'span'}>
                  when ready to be formally considered by the dArtFlex DAO, a Governance Proposal is entered and made
                  available for voting on{' '}
                  <Link href={'https://snapshot.page/#'} className={classes.navLink}>
                    https://snapshot.page/#
                  </Link>
                </Typography>
              </Box>
            </li>
            <li className={classes.unorderedListItem}>
              <Box display="flex">
                <Box mr={2}>-</Box>
                <Typography variant={'body2'} component={'span'}>
                  during the voting period (typically seven days), eligible DAF holders may vote their eligible DAF on
                  the Governance Proposal through{' '}
                  <Link href={'https://snapshot.page/#'} className={classes.navLink}>
                    https://snapshot.page/#
                  </Link>{' '}
                  with each whole eligible DAF entitling the holder to a single vote on each Governance Proposal (and
                  each fractional eligible DAF entitling the holder to a corresponding fractional vote);
                </Typography>
              </Box>
            </li>
            <li className={classes.unorderedListItem}>
              <Box display="flex">
                <Box mr={2}>-</Box>
                <Typography variant={'body2'} component={'span'}>
                  eligibility of DAF to vote on each Governance Proposal is based on a “snapshot” of DAF account
                  balances on Ethereum at a specific block of the Ethereum blockchain prior to commencement of the
                  voting period for such Governance Proposal;
                </Typography>
              </Box>
            </li>
            <li className={classes.unorderedListItem}>
              <Box display="flex">
                <Box mr={2}>-</Box>
                <Typography variant={'body2'} component={'span'}>
                  the official determination of the dArtFlex DAO on the Governance Proposal will be the determination
                  supported by a simple majority of the DAF that were actually voted on such Governance Proposal;
                </Typography>
              </Box>
            </li>
            <li className={classes.unorderedListItem}>
              <Box display="flex">
                <Box mr={2}>-</Box>
                <Typography variant={'body2'} component={'span'}>
                  there is no quorum (minimum number of DAF voting) required for the dArtFlex DAO to make a
                  determination on a Governance Proposal; and
                </Typography>
              </Box>
            </li>
            <li className={classes.unorderedListItem}>
              <Box display="flex">
                <Box mr={2}>-</Box>
                <Typography variant={'body2'} component={'span'}>
                  voters are only pseudonymously identifiable by Ethereum address; accordingly, there is no reasonably
                  practicable method of verifying the identities or interests of voters and there are no express rules
                  regarding recusal of voters or disqualification of votes based on conflicts of interest or other
                  similar factors; however, dArtFlex Company may take any evidence of conflicts of interest or other
                  issues regarding specific voters that comes to the attention of dArtFlex Company into account in
                  determining whether and how to implement determinations of the dArtFlex DAO in Governance Decisions.
                </Typography>
              </Box>
            </li>
          </ul>
          <Typography className={classes.sectionTitle}>4. SUPPLY, ALLOCATION AND DISTRIBUTION OF DAF </Typography>
          <Typography variant={'h4'}>4.1 dArtFlex Supply. </Typography>
          <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
            The total number of DAF is fixed at
            <strong> 80,000,000 DAF</strong> (the “TotalSupply”).
          </Typography>
          <Typography variant={'h4'} className={classes.textBlockMargin24}>
            4.2 Overview of DAF Allocation and Distribution.{' '}
          </Typography>
          <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
            (a) dArtFlex Company has published its intention to allocate the TotalSupply as follows:
          </Typography>
          <ul className={classes.unorderedListInitial}>
            {allocationDistribution.map((item, index) => {
              return (
                <li className={classes.unorderedListItem} key={index}>
                  <Typography variant={'body2'} component={'span'}>
                    {item}
                  </Typography>
                </li>
              )
            })}
          </ul>
          <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
            (b) All questions concerning the interpretation and implementation of such allocation principles and the
            eligibility of a given person to receive DAF or the specific amount of DAF to be received by an eligible
            person out of the ReserveSupply, AirdropSupply, MiningSupply or otherwise, as applicable, shall be
            determined: during the Signaling Era, in the sole and absolute discretion of dArtFlex Company or a special
            purpose vehicle or foundation established by the dArtFlex Company to hold DAF; and (ii) during the
            Autonomous Era, by the dArtFlex DAO.
          </Typography>
          <Typography variant={'h4'} className={classes.textBlockMargin24}>
            4.3 Certain Eligibility Requirements of DAF Recipients.
          </Typography>
          <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
            Notwithstanding anything to the contrary set forth in Section 7.2(a), and without limiting the generality of
            Section 7.2(b), dArtFlex Company shall not be required or obligated to distribute any DAF (out of the
            AirDropSupply, MiningSupply, or otherwise) to, or honor the voting or other rights of DAF held by, any
            person who, as determined in the sole and absolute discretion of dArtFlex Company, directly or indirectly,
            in connection with the use of the dArtFlex Platform, dArtFlex Apps, dArtFlex DEX System, dArtFlex DAO, DAF
            or any transactions involving NFTs or Collectibles, has violated these Terms, including any use of the
            Offerings set forth in Section 5.2. Examples of disqualifying events include engaging in frontrunning,”
            “wash trading,” “pump and dump trading,” “ramping,” “cornering” or other fraudulent, deceptive or
            manipulative trading activities, or engaging in or facilitating ICOs or other financing transactions, for
            the purpose of increasing such user’s DAF rewards or otherwise.
          </Typography>
          <Typography className={classes.sectionTitle}>5. REPRESENTATIONS AND WARRANTIES OF DAF RECIPIENTS </Typography>
          <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
            Each User hereby represents and warrants to dArtFlex Company that the following statements and information
            are accurate and complete at all relevant times. In the event that any such statement or information becomes
            untrue as to a User, User shall immediately divest and cease using all DAF and cease accessing and using all
            other Offerings.
          </Typography>
          <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
            If User is an individual, User is of legal age in the jurisdiction in which User resides (and in any event
            is older than thirteen years of age) and is of sound mind. If User is a business entity, User is duly
            organized, validly existing and in good standing under the laws of the jurisdiction in which it is
            organized, and has all requisite power and authority for a business entity of its type to carry on its
            business as now conducted.
          </Typography>
          <Typography variant={'h4'} className={classes.textBlockMargin24}>
            5.2 Power and Authority.
          </Typography>
          <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
            Users have all requisite capacity, power and authority to accept the terms and conditions of these Terms and
            to carry out and perform its obligations under these Terms. These Terms constitute a legal, valid and
            binding obligation of User enforceable against User in accordance with its terms.
          </Typography>
          <Typography variant={'h4'} className={classes.textBlockMargin24}>
            5.3 No Conflict;
          </Typography>
          <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
            Compliance with law. User agreeing to these Term and buying, selling holding, using or receiving DAF does
            not constitute, and would not reasonably be expected to result in (with or without notice, lapse of time, or
            both) a breach, default, contravention or violation of any law applicable to User, or contract or agreement
            to which User is a party or by which User is bound.
          </Typography>
          <Typography variant={'h4'} className={classes.textBlockMargin24}>
            5.4 Absence of Sanctions.
          </Typography>
          <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
            User is not, (and, if User is an entity, User is not owned or controlled by any other person who is), and is
            not acting on behalf of any other person who is, identified on any list of prohibited parties under any law
            or by any nation or government, state or other political subdivision thereof, any entity exercising
            legislative, judicial or administrative functions of or pertaining to government such as the lists
            maintained by the United Nations Security Council, the U.S. government (including the U.S. Treasury
            Department’s Specially Designated Nationals list and Foreign Sanctions Evaders list), the European Union
            (EU) or its member states, and the government of a User home country. User is not, (and, if User is an
            entity, User is not owned or controlled by any other person who is), and is not acting on behalf of any
            other person who is, located, ordinarily resident, organized, established, or domiciled in Cuba, Iran, North
            Korea, Sudan, Syria, the Crimea region (including Sevastopol) or any other country or jurisdiction against
            which the U.S. maintains economic sanctions or an arms embargo. The tokens or other funds a User uses to
            participate in the dArtFlex Platform or acquire Collectibles or DAF are not derived from, and do not
            otherwise represent the proceeds of, any activities done in violation or contravention of any law.
          </Typography>
          <Typography variant={'h4'} className={classes.textBlockMargin24}>
            5.5 No Claim, Loan, Ownership Interest or Investment Purpose.
          </Typography>
          <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
            User understands and agrees that the User’s purchase, sale, holding, receipt and use of DAF and the other
            Offerings does not: 12 (a) represent or constitute a loan or a contribution of capital to, or other
            investment in dArtFlex Company or any business or venture; (b) provide User with any ownership interest,
            equity, security, or right to or interest in the assets, rights, properties, revenues or profits of, or
            voting rights whatsoever in, dArtFlex Company or any other business or venture; and (c) create or imply or
            entitle User to the benefits of any fiduciary or other agency relationship between dArtFlex Company or any
            of its directors, officers, employees, agents or affiliates, on the on hand, and User, on the other hand.
            User is not entering into these Terms or buying, selling, holding receiving or using DAF for the purpose of
            making an investment with respect to dArtFlex Company or its securities, but solely wishes to use the
            dArtFlex Platform for its intended purposes and participate in the dArtFlex DAO in order to participate in
            the protection and improvement of the use and enjoyment of the dArtFlex Platform for such purposes. User
            understands and agrees that dArtFlex Company will not accept or take custody over any Collectibles, DAF,
            cryptocurrencies or other assets of User and has no responsibility or control over the foregoing.
          </Typography>
          <Typography variant={'h4'} className={classes.textBlockMargin24}>
            5.6 Non-Reliance.
          </Typography>
          <Typography variant={'body2'} component={'div'} className={classes.textBlockTight}>
            Users are knowledgeable, experienced and sophisticated in using and evaluating blockchain and related
            technologies and assets, including Ethereum, NFTs, Collectibles and “smart contracts” (bytecode deployed to
            Ethereum or another blockchain). User has conducted its own thorough independent investigation and analysis
            of the dArtFlex Platform, DAF and the other matters contemplated by these Terms, and has not relied upon any
            information, statement, omission, representation or warranty, express or implied, written or oral, made by
            or on behalf of dArtFlex Company in connection therewith, except as expressly set forth by dArtFlex Company
            in these Terms.
          </Typography>
        </Box>
      </>
    </AuxiliaryPage>
  )
}
